# Generated by Django 5.1.4 on 2024-12-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LabApparelRequest',
            fields=[
                ('control_number', models.AutoField(primary_key=True, serialize=False)),
                ('course_and_year', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('date_borrowed', models.DateField()),
                ('time_borrowed', models.TimeField()),
                ('borrowed_item', models.CharField(choices=[('lab_gown', 'Lab Gown'), ('lab_apron', 'Lab Apron')], max_length=50)),
                ('teacher_approval', models.BooleanField(default=False)),
                ('labtech_approval', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved by Teacher'), ('borrowed', 'Borrowed'), ('returned', 'Returned')], default='pending_approval', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('material_type', models.CharField(choices=[('reagent', 'Reagent'), ('material', 'Material')], default='material', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialInRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[(None, 'None'), ('g', 'Grams'), ('mg', 'Milligrams'), ('mL', 'Milliliters'), ('L', 'Liters'), ('mol/L', 'Molarity'), ('mol/kg', 'Molality'), ('%', 'Mass Percentage'), ('% v/v', 'Volume Percentage'), ('ppm', 'Parts Per Million')], default=None, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('altered', 'Altered'), ('ready', 'Ready'), ('waiting_return', 'Waiting Return'), ('returned', 'Returned'), ('broken', 'Broken'), ('used', 'Used')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('control_number', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('experiment_number', models.CharField(max_length=50)),
                ('group_number', models.CharField(max_length=50)),
                ('date_of_experiment', models.DateField()),
                ('time_of_experiment', models.TimeField()),
                ('title_of_experiment', models.CharField(max_length=200)),
                ('teacher_approval', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved by Teacher'), ('processing', 'Processing'), ('ready', 'Ready'), ('borrowed', 'Borrowed'), ('returned', 'Returned'), ('has_liabilities', 'Has Liabilities')], default='pending_approval', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
    ]
