# Generated by Django 5.1.4 on 2024-12-12 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labapparelrequest',
            name='approved_by_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_lab_apparel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labapparelrequest',
            name='noted_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'lab_technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noted_borrow_lab_apparel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liability',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrow.material'),
        ),
        migrations.AddField(
            model_name='materialinrequest',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrow.material'),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'lab_technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'user_type': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialinrequest',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='borrow.materialrequest'),
        ),
        migrations.AddField(
            model_name='liability',
            name='material_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrow.materialrequest'),
        ),
        migrations.AddField(
            model_name='group',
            name='materials_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='borrow.materialrequest'),
        ),
        migrations.AddField(
            model_name='liability',
            name='group_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrow.student'),
        ),
        migrations.AddField(
            model_name='labapparelrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrow.student'),
        ),
        migrations.AddField(
            model_name='group',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_leader', to='borrow.student'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='group_member', to='borrow.student'),
        ),
    ]
