# Generated by Django 5.1.4 on 2024-12-14 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'user_type': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iteminrequest',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='borrow.materialrequest'),
        ),
        migrations.AddField(
            model_name='group',
            name='materials_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='borrow.materialrequest'),
        ),
        migrations.AddField(
            model_name='request',
            name='lab_technician',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'lab_technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noted_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material_request', to='borrow.request'),
        ),
        migrations.AddField(
            model_name='liability',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrow.request'),
        ),
        migrations.AddField(
            model_name='labapparelrequest',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_apparel_request', to='borrow.request'),
        ),
        migrations.AddField(
            model_name='liability',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrow.student'),
        ),
        migrations.AddField(
            model_name='labapparelrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrow.student'),
        ),
        migrations.AddField(
            model_name='group',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_leader', to='borrow.student'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='group_member', to='borrow.student'),
        ),
    ]
