# Generated by Django 5.1.4 on 2024-12-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('reagent', 'Reagent'), ('material', 'Material'), ('equipment', 'Equipment')], default='material', max_length=20),
        ),
    ]
