# Generated by Django 5.1.4 on 2024-12-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_alter_material_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('altered', 'Altered'), ('ready', 'Ready'), ('borrowed', 'Borrowed'), ('returned', 'Returned'), ('broken', 'Broken'), ('used', 'Used')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved by Teacher'), ('denied', 'Denied'), ('processing', 'Processing'), ('ready', 'Ready'), ('borrowed', 'Borrowed'), ('returned', 'Returned')], default='pending_approval', max_length=50),
        ),
    ]
