# Generated by Django 5.1.4 on 2024-12-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminrequest',
            name='unit',
            field=models.CharField(choices=[('None', 'N/A'), ('g', 'Grams'), ('mg', 'Milligrams'), ('mL', 'Milliliters'), ('L', 'Liters')], default=None, max_length=20, null=True),
        ),
    ]
