# Generated by Django 5.1.4 on 2024-12-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0004_alter_iteminrequest_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labapparelrequest',
            name='date_borrowed',
        ),
        migrations.RemoveField(
            model_name='labapparelrequest',
            name='time_borrowed',
        ),
    ]
