# Generated by Django 5.1.4 on 2024-12-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0004_alter_materialinrequest_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labapparelrequest',
            old_name='noted_by',
            new_name='lab_technician',
        ),
        migrations.RenameField(
            model_name='labapparelrequest',
            old_name='approved_by_teacher',
            new_name='teacher',
        ),
        migrations.AlterField(
            model_name='materialinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('denied', 'Denied'), ('ready', 'Ready'), ('borrowed', 'Borrowed'), ('returned', 'Returned'), ('broken', 'Broken'), ('used', 'Used')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved by Teacher'), ('denied', 'Denied'), ('ready', 'Ready'), ('borrowed', 'Borrowed'), ('returned', 'Returned')], default='pending_approval', max_length=50),
        ),
    ]
