# Generated by Django 5.1.4 on 2024-12-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0005_rename_noted_by_labapparelrequest_lab_technician_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='liability'
        ),
    ]
