# Generated by Django 5.1.4 on 2024-12-16 17:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0007_alter_iteminrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('restock', 'Restock'), ('usage', 'Usage'), ('return', 'Return')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='borrow.material')),
            ],
        ),
    ]
