# Generated by Django 5.1.4 on 2024-12-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0008_alter_materialrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='liability',
            name='remarks',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='materialinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('denied', 'Denied'), ('ready', 'Ready'), ('borrowed', 'Borrowed'), ('returned', 'Returned'), ('broken', 'Broken/Lost'), ('used', 'Used')], default='pending', max_length=20),
        ),
    ]
